[package]
name = "axum-site"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[package.metadata.cargo-machete]
ignored = ["derive-new", "color-eyre", "serde", "tokio", "v_utils"]

[lints.clippy]
float_cmp = "allow" # is bad for `==` direct comparisons, but `<` and `>` should be allowed
#get_first = "allow" # const fn, so actually more performant
len_zero = "allow" # `.empty()` is O(1) but on &str only
undocumented_unsafe_blocks = "warn"
tabs_in_doc_comments = "allow"

[dependencies]
axum = { version = "^0.7.9", features = ["http2", "macros", "ws"] }
chrono = "^0.4.38"
color-eyre = "^0.6.3"
derive-new = "^0"
function_name = "^0.3.0"
futures = { version = "^0.3.31", features = ["compat"] }
plotly = { version = "^0.10.0", features = ["kaleido"] }
polars = { version = "^0.44.2", features = ["polars-io"] }
reqwest = { version = "^0.12.9", features = ["json"] }
serde = { version = "^1.0.215", features = ["derive"] }
serde_json = "^1.0.133"
serde_path_to_error = "^0.1.16"
serde_with = "3.11.0"
tokio = { version = "^1.41.1", features = ["full"] }
v_utils = { version = "^1.9.1", features = ["trades"], path = "../v_utils/v_utils" }
