env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_RETRY: '10'
  RUSTUP_MAX_RETRIES: '10'
  RUST_BACKTRACE: short
jobs:
  pre_ci:
    uses: valeratrades/.github/.github/workflows/pre_ci.yml@master
  test:
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cat Cargo.toml
name: dbg
'on':
  workflow_dispatch: {}
permissions:
  contents: read
